import Head from 'next/head'
import Header from '@/src/components/header/header'
import Footer from '@/src/components/footer/footer'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
       <div>
       <section>
            <h2>Equipe Bet on Tech (Bot)</h2>
            <p>

                Caio Cesar Aruda. RM: 99456 <a href="https://github.com/caiioo0"><img src="githublogo.png"
                            alt="github" title="github"/></a>
                Julianny Araujo Pereira. RM: 99554 <a href="https://github.com/JuliannyAraujo"><img
                            src="githublogo.png" alt="github" title="github"/></a>;
                Karen Vitoria Jesus da Silva. RM: 99468 <a href="https://github.com/Kavitooria"><img
                            src="githublogo.png" alt="github" title="github"/></a>;
                Matheus Matos Pereira. RM: 99792 <a href="https://github.com/matheusp94"><img src="githublogo.png"
                            alt="github" title="github"/></a>.
            </p>
        </section>
      <Footer/>
        </div>

    </>
  )
}